version: "2"
services:
    www:
        build: .
        ports: 
            - "80:80"
            - "443:443"
        #volumes:
          #  - ./www:/var/www/html/
          #  - ./:/var/www/html/
        networks:
            prologmud_vlan:
                ipv4_address: 10.0.0.99
networks:
  nginx_vlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

volumes:
  - . /opt/logicmoo_workspace
    persistent:

